Aqsh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('registration/', include('registration.urls')),
    path('offer/', include('offer.urls')),
    path('notification/', include('notification.urls')),
    path('search/', include('search.urls')),
    path('admin/', admin.site.urls),
]

notification/urls.py
from django.urls import path

from .import views

app_name = "notification"

urlpatterns = [
    path('', views.index, name='index'),
    path('save/', views.apply_save, name='apply_save'),
    path('apply_list/', views.ApplyListView.as_view(), name='apply_list'),
    path('detail/<int:pk>/', views.ApplyDetailView.as_view(), name='apply_list_detail'),
    path('hiring_save/', views.hiring_save, name='hiring_save'),
    path('hiring_list/', views.HiringListView.as_view(), name='hiring_list'),
]

offer/urls.py
from django.urls import path

from .import views

app_name = "offer"

urlpatterns = [
    path('', views.offer, name='offer'),
    path('save/', views.offer_save, name='offer_save'),
    path('list', views.OfferListView.as_view(), name='offer_list'),
    path('detail/<int:pk>/', views.OfferDetailView.as_view(), name='offer_list_detail'),
]

registration/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .forms import LoginForm

from .import views

app_name = "registration"

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('regist/', views.regist, name='regist'),
    path('regist_save/', views.regist_save, name='regist_save'),
    path('role/', views.role, name='role'),
    path('recruiter/', views.recruiter, name='recruiter'),
    path('recruiter_save/', views.recruiter_save, name='recruiter_save'),
    path('jobseeker/', views.jobseeker, name='jobseeker'),
    path('jobseeker_save/', views.jobseeker_save, name='jobseeker_save'),
    path('desired_condition/', views.desired_condition, name='desired_condition'),
    path('desired_condition_save/', views.desired_condition_save, name='desired_condition_save'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

search/urls.py
from django.urls import path
from .import views

app_name = "search"

urlpatterns = [
    path('', views.UserListView.as_view(), name='job_seekers_list'),
    path('detail/<int:pk>/', views.UserDetailView.as_view(), name='job_seekers_detail'),
]

offer/models.py
from django.db import models
from django.utils import timezone

from registration.models import Recruiter, JobSeeker


class OfferList(models.Model):

    EMPLOYMENT_CHOICES = (
        ('正社員', '正社員'),
        ('契約社員', '契約社員'),
        ('アルバイト', 'アルバイト'),
        ('派遣社員', '派遣社員'),
        ('その他', 'その他'),
    )

    recruiter = models.ForeignKey(Recruiter, verbose_name='リクルーター', on_delete=models.CASCADE)
    job_seeker = models.ForeignKey(JobSeeker, verbose_name='求職者', on_delete=models.CASCADE)
    job_name = models.CharField(max_length=20, verbose_name='案件名')
    job_details = models.CharField(max_length=250, verbose_name='案件詳細')
    offer_amount = models.IntegerField(verbose_name='オファー金額')
    work_location = models.CharField(max_length=30, verbose_name='勤務地')
    work_period = models.CharField(max_length=30, verbose_name='勤務期間')
    reply_deadline = models.DateField(verbose_name='応募期限', default=timezone.now)
    Employment_status = models.CharField(max_length=5, verbose_name='雇用形態', choices=EMPLOYMENT_CHOICES)
    date_offered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.recruiter.user.full_name+'さんの案件「'+self.job_name+'」'

offer/forms.py
from django.forms import forms

from offer.models import OfferList
from django import forms


class OfferForm(forms.ModelForm):
    class Meta:
        model = OfferList
        fields = ('recruiter',
                  'job_seeker',
                  'job_name',
                  'job_details',
                  'offer_amount',
                  'work_location',
                  'work_period',
                  'reply_deadline',
                  'Employment_status'
                  )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['job_name'].widget.attrs['class'] = 'form-control'
        self.fields['job_details'].widget.attrs['class'] = 'form-control'
        self.fields['offer_amount'].widget.attrs['class'] = 'form-control'
        self.fields['work_location'].widget.attrs['class'] = 'form-control'
        self.fields['work_period'].widget.attrs['class'] = 'form-control'
        self.fields['reply_deadline'].widget.attrs['class'] = 'form-control'
        self.fields['Employment_status'].widget.attrs['class'] = 'form-control'

offer/views.py
import os
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.views import generic
from django.views.generic import ListView

from Aqsh.settings import EMAIL_HOST_USER
from offer.models import OfferList
from registration.models import JobSeeker, Recruiter
from offer.forms import OfferForm
from django.core.mail import EmailMessage


class OfferListView(ListView):
    model = OfferList
    context_object_name = 'offer_list'
    template_name = 'offer_list.html'

    def get_queryset(self):
        user = self.request.user
        target_object = JobSeeker.objects.get(user_id=user.id)
        my_job_seeker_id = target_object.id
        return OfferList.objects.filter(job_seeker_id=my_job_seeker_id)


class OfferDetailView(generic.DetailView):
    model = OfferList
    template_name = 'offer_list_detail.html'


def index(request):
    return HttpResponse("Hello, world. You're at the offer index.")


def offer(request):
    form = OfferForm(request.POST or None)

    context = {
        'form': form,
        'user': request.user,
        'job_seeker_id': request.GET['id_no'],
    }

    return render(request, 'offer.html', context)


@require_POST
def offer_save(request):
    form = OfferForm(request.POST)
    job_seeker_id = int(request.POST['job_seeker'])
    job_name = request.POST['job_name']
    recruiter_id = request.POST['recruiter']

    if form.is_valid():
        form.save(commit=True)
        target_job_seeker = JobSeeker.objects.get(pk=job_seeker_id)
        to_email = target_job_seeker.user.email
        target_recruiter = Recruiter.objects.get(pk=recruiter_id)
        recruiter_name = target_recruiter.user.username

        subject = "Aqshアプリより「" + job_name + "」のオファーのお知らせ"
        message = recruiter_name + "さんからオファーが届いています。Aqshアプリにアクセスして内容をご確認ください。"
        from_email = EMAIL_HOST_USER
        recipient_list = to_email  # 宛先
        email = EmailMessage(subject, message, from_email,  [recipient_list])
        email.send()

        return redirect('search:job_seekers_list')

    context = {
        'form': form,
    }
    return render(request, 'offer.html', context)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Aqsh</title>
      <!-- BootstrapのCSS読み込み -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
      <!-- jQuery読み込み -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
      <!-- BootstrapのJS読み込み -->
      <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}"/>
  </head>

  <body>
  <nav class="navbar navbar-expand-sm navbar-dark mt-0 mb-3" style="background-color:royalblue;">
      <a class="navbar-brand" href="{% url 'registration:index' %}"><img src="{% static 'Aqsh/Aqsh_logo.png' %}"
                                                                         width="105" height="60"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4"
              aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse">
          <ul class="navbar-nav">
              {% if user.is_authenticated %}
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url 'registration:logout' %}">ログアウト</a>
                  </li>
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url 'registration:profile' %}">登録情報</a>
                  </li>
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url 'registration:role' %}">詳細登録</a>
                  </li>
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url 'search:job_seekers_list' %}">求職者検索画面</a>
                  </li>
                  {% if user.jobseeker_set.first.offerlist_set.first.id %}
                      <li class="nav-item active">
                      <a class="nav-link" href="{% url 'offer:offer_list' %}">求人案件一覧</a>
                      </li>
                  {% endif %}
                  {% if user.recruiter_set.first.offerlist_set.first.id %}
                      <li class="nav-item active">
                      <a class="nav-link" href="{% url 'notification:apply_list' %}">オファーへの返信状況一覧</a>
                      </li>
                  {% endif %}
                  {% if user.jobseeker_set.first.offerlist_set.first.id %}
                      <li class="nav-item active">
                      <a class="nav-link" href="{% url 'notification:hiring_list' %}">応募案件への返信状況一覧</a>
                      </li>
                  {% endif %}
          {% else %}
                  <li class="nav-item active">
            <a class="nav-link" href="{% url 'registration:login' %}">ログイン</a>
                  </li>
                  <li class="nav-item active">
            <a class="nav-link" href="{% url 'registration:regist' %}">ユーザ登録</a>
                  </li>
              {% endif %}
          </ul>
      </div>
  </nav>

  {% if user.is_authenticated %}
      <span class="navbar-text">ようこそ {{ user.get_username }}さん</span>
  {% endif %}

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  <div class="container">
      {% block content %}
      {% endblock %}
  </div>
  </body>
</html>

templates/desired_condition.html
{% extends "base.html" %}
{% block content %}

<form class="my-form" action="{% url 'registration:desired_condition_save' %}" method="POST">
{% csrf_token %}
<div>
    <H2>■ 希望条件登録 ■</H2>
</div>
  <div class="form-group">
    <label for="id_skills">スキル</label>
    {{ form.skills }}
    {{ form.skills.errors }}
    <p class="help-block">{{ form.skills.help_text }}</p>
  </div>

  <div class="form-group">
    <label for="id_job_change">転職 or 副業</label>
    {{ form.job_change }}
    {{ form.job_change.errors }}
    <p class="help-block">{{ form.job_change.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_monthly_income">希望月収</label>
    {{ form.monthly_income }}円
    {{ form.monthly_income.errors }}
  </div>


  <div class="form-group">
    <label class="control-label" for="id_hourly_wage">希望時給</label>
      {{ form.hourly_wage }}円
      {{ form.hourly_wage.errors }}
      <p class="help-block">{{ form.hourly_wage.help_text }}</p>
  </div>

  <input type="hidden" name="job_seeker" value="{{ user.jobseeker_set.first.id }}">

  <div class="form-group">
    <div>
        <input type="submit" class="btn btn-primary" value="登録">
    </div>
  </div>

</form>
{% endblock content %}

templates/hiring_list.html
{% extends "base.html" %}
{% block content %}

    <ul>
        <div><h2>返信状況一覧</h2></div>
        <hr>
        {% for item in object_list %}
            <div>
                <p>案件名:{{ item.job_seeker_notice.offer_list.job_name }}</p>
                <p>担当者名:{{ item.job_seeker_notice.offer_list.recruiter.user.username }}</p>
                <p>返信:{{ item.hiring }}</p>
                <p>返信日時:{{ item.date_hire }}</p>
                {#                <a href="{% url 'notification:apply_list_detail' item.pk %}" class="card-link">詳細を見る</a>#}
                <hr>
            </div>

        {% endfor %}
    </ul>

{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <form class="my-form">
    <h1>Aqshアプリ トップページ</h1>
    </form>
{% endblock content %}

templates/job_seekers_detail.html
{% extends "base.html" %}
{% block content %}

    <div class="bg-light">
  <h4 class="alert-heading">{{ user.username }}さんのプロフィール</h4>
  <p>性別 : {{ user.jobseeker_set.first.gender }}</p>
  <p>住所 : {{ user.jobseeker_set.first.address }}</p>
  <p>最終学歴 : {{ user.jobseeker_set.first.Academic_history }}</p>
  <p>スキル : {{ user.jobseeker_set.first.desiredcondition_set.first.skills }}</p>
  <p>検討状況 : {{ user.jobseeker_set.first.desiredcondition_set.first.job_change }}</p>
  <p>希望月収 : {{ user.jobseeker_set.first.desiredcondition_set.first.monthly_income }}</p>
  <p>希望時給 : {{ user.jobseeker_set.first.desiredcondition_set.first.hourly_wage }}</p>
  <p class="text-muted">登録日 : {{ user.date_joined }}</p>
  <p class="text-muted">最終ログイン日 : {{ user.last_login }}</p>
    <p><a class="btn btn-primary" href="{% url 'offer:offer' %}?id_no={{ user.jobseeker_set.first.id }}"
          onclick="document.form1.submit();return false;">
      {{ user.username }}さんにオファーする</a></p>
  <p><a class="btn btn-primary" href="javascript:void(0);" onclick="window.history.back();">戻る</a></p>
</div>

{% endblock content %}

templates/job_seekers_list.html
{% extends "base.html" %}
{% block content %}

<ul>
<div><h2>求職者一覧</h2></div>
<hr>
  {% for item in object_list %}
            <div>
            <p>{{ item.username }}さん</p>
            <p>{{ item.jobseeker_set.first.gender }}</p>
            <p>{{ item.jobseeker_set.first.address }}</p>
            <p>{{ item.jobseeker_set.first.desiredcondition_set.first.skills }}</p>
            <p>{{ item.jobseeker_set.first.desiredcondition_set.first.job_change }}</p>
                <a class="btn btn-primary" href="{% url 'search:job_seekers_detail' item.pk %}" class="card-link">プロフィールを見る</a>
            <hr>
            </div>

  {% endfor %}
</ul>

{% endblock content %}

templates/jobseeker.html
{% extends "base.html" %}
{% block content %}

<form class="my-form" action="{% url 'registration:jobseeker_save' %}" method="POST">
{% csrf_token %}
<div>
    <H2>■ 詳細情報登録 ■</H2>
</div>
    {% if user.jobseeker_set.first.id %}
        {% if user.jobseeker_set.first.desiredcondition_set.first.id %}
            <p>既に登録頂いております。オファーを待ちましょう。</p>
            <a class="btn btn-primary" href="{% url 'registration:index' %}">戻る</a>
        {% else %}
            <p>既にオファーが受けられる状態です。希望条件を登録することでオファーが受けやすくなります。</p>
            <a class="btn btn-primary" href="{% url 'registration:desired_condition' %}">希望条件の登録へ</a>
        {% endif %}

    {% else %}
  <div class="form-group">
    <label for="id_gender">性別</label>
    {{ form.gender }}
    {{ form.gender.errors }}
    <p class="help-block">{{ form.gender.help_text }}</p>
  </div>

  <div class="form-group">
    <label for="id_date_of_birth">生年月日</label>
    {{ form.date_of_birth }}
    {{ form.date_of_birth.errors }}
    <p class="help-block">{{ form.date_of_birth.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_postal_code">郵便番号</label>
    {{ form.postal_code }}
    {{ form.postal_code.errors }}
  </div>


  <div class="form-group">
    <label class="control-label" for="id_address">住所</label>
      {{ form.address }}
      {{ form.address.errors }}
      <p class="help-block">{{ form.address.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_nearest_station">最寄り駅</label>
      {{ form.nearest_station }}
      {{ form.nearest_station.errors }}
      <p class="help-block">{{ form.nearest_station.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_phone_number">電話番号</label>
      {{ form.phone_number }}
      {{ form.phone_number.errors }}
      <p class="help-block">{{ form.phone_number.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_Academic_history">最終学歴</label>
      {{ form.Academic_history }}
      {{ form.Academic_history.errors }}
      <p class="help-block">{{ form.Academic_history.help_text }}</p>
  </div>

  <input type="hidden" name="user" value="{{ user.id }}">

  <div class="form-group">
    <div>
        <input type="submit" class="btn btn-primary" value="登録">
    </div>
  </div>

</form>
    {% endif %}
{% endblock content %}

templates/login.html
{% extends "base.html" %}
{% block content %}
 
<form class="my-form" action="{% url 'registration:login' %}" method="POST">
  <div class="form-group">
    <label for="id_email">ユーザーネーム</label>
    {{ form.username }}
    {{ form.username.errors }}
  </div>
 
  <div class="form-group">
    <label for="id_password">パスワード</label>
    {{ form.password }}
    {{ form.password.errors }}
  </div>
 
  <div class="form-group">
    <div>
        <input type="submit" class="btn btn-primary" value="ログイン">
    </div>
  </div>
 
  <input type="hidden" name="next" value="{{ index }}"/>
  {% csrf_token %}
 
</form>
{% endblock content %}

templates/offer.html
{% extends "base.html" %}
{% block content %}

<form class="my-form" action="{% url 'offer:offer_save' %}" method="POST">
{% csrf_token %}

  <div class="form-group">
    <label for="id_job_name">案件名</label>
    {{ form.job_name }}
    {{ form.job_name.errors }}
    <p class="help-block">{{ form.job_name.help_text }}</p>
  </div>

  <div class="form-group">
    <label for="id_job_details">案件詳細</label>
    {{ form.job_details }}
    {{ form.job_details.errors }}
    <p class="help-block">{{ form.job_details.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_offer_amount">オファー金額</label>
    {{ form.offer_amount }}円
    {{ form.offer_amount.errors }}
  </div>


  <div class="form-group">
    <label class="control-label" for="id_work_location">勤務地</label>
      {{ form.work_location }}
      {{ form.work_location.errors }}
      <p class="help-block">{{ form.work_location.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_work_period">勤務期間</label>
      {{ form.work_period }}
      {{ form.work_period.errors }}
      <p class="help-block">{{ form.work_period.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_reply_deadline">応募期限</label>
      {{ form.reply_deadline }}
      {{ form.reply_deadline.errors }}
      <p class="help-block">{{ form.reply_deadline.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_Employment_status">雇用形態</label>
      {{ form.Employment_status }}
      {{ form.Employment_status.errors }}
      <p class="help-block">{{ form.Employment_status.help_text }}</p>
  </div>

  <input type="hidden" name="job_seeker" value="{{ job_seeker_id }}">
  <input type="hidden" name="recruiter" value="{{ user.recruiter_set.first.id }}">

  <div class="form-group">
    <div>
        <input type="submit" class="btn btn-primary" value="送信">
    </div>
  </div>

</form>
{% endblock content %}

templates/offer_list.html
{% extends "base.html" %}
{% block content %}

<ul>
<div><h2>求人案件一覧</h2></div>
<hr>
  {% for item in object_list %}
            <div>
            <p>案件名:{{ item.job_name }}</p>
            <p>提示金額:{{ item.offer_amount }}</p>
            <p>勤務地:{{ item.work_location }}</p>
            <p>雇用形態:{{ item.Employment_status }}</p>
            <p>案件発生日:{{ item.date_offered }}</p>
                <a class="btn btn-primary" href="{% url 'offer:offer_list_detail' item.pk %}"
                   class="card-link">詳細を見る</a>
            <hr>
            </div>

  {% endfor %}
</ul>

{% endblock content %}

templates/offer_list_detail.html
{% extends "base.html" %}
{% block content %}

    <div class="bg-light">
  <h4 class="alert-heading">案件{{ offerlist.job_name }}の詳細</h4>
  <p>内容 : {{ offerlist.job_details }}</p>
  <p>提示金額 : {{ offerlist.offer_amount }}</p>
  <p>会社名 : {{ offerlist.recruiter.company_name }}</p>
    <p>担当者名 : {{ offerlist.recruiter.user.username }}</p>
  <p>勤務地 : {{ offerlist.work_location }}</p>
  <p>期間 : {{ offerlist.work_period }}</p>
  <p>雇用形態 : {{ offerlist.Employment_status }}</p>
  <p>案件発生日 : {{ offerlist.date_offered }}</p>
  <p>応募期限 : {{ offerlist.reply_deadline }}</p>

</div>

    <form class="my-form" action="{% url 'notification:apply_save' %}" method="POST">
        {% csrf_token %}

        <input type="hidden" name="offer_list" value="{{ offerlist.id }}">
        <div class="form-group">
            <div>
                <input type="hidden" name="apply_offer" value="応募する">
                <input type="submit" class="btn btn-primary" value="応募する">
            </div>
        </div>

    </form>

    <form class="my-form" action="{% url 'notification:apply_save' %}" method="POST">
        {% csrf_token %}

        <input type="hidden" name="offer_list" value="{{ offerlist.id }}">
        <div class="form-group">
            <div>
                <input type="hidden" name="apply_offer" value="辞退する">
                <input type="submit" class="btn btn-primary" value="辞退する">
            </div>
        </div>

    </form>
    <p><a class="btn btn-primary" href="javascript:void(0);" onclick="window.history.back();">戻る</a></p>

{% endblock content %}

templates/recruiter.html
{% extends "base.html" %}
{% block content %}

<form class="my-form" action="{% url 'registration:recruiter_save' %}" method="POST">

<div>
    <H2>■ 詳細情報登録 ■</H2>
</div>

{% csrf_token %}
    {% if user.recruiter_set.first.id %}
        <p>既に登録頂いております。求職者へオファーを送りましょう。</p>
        <a class="btn btn-primary" href="{% url 'search:job_seekers_list' %}">求職者検索へ</a>
    {% else %}
  <div class="form-group">
    <label for="id_company_name">会社名</label>
    {{ form.company_name }}
    {{ form.company_name.errors }}
    <p class="help-block">{{ form.company_name.help_text }}</p>
  </div>

  <div class="form-group">
    <label for="id_ruby_company_name">ふりがな(会社名)</label>
    {{ form.ruby_company_name }}
    {{ form.ruby_company_name.errors }}
    <p class="help-block">{{ form.ruby_company_name.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_postal_code">郵便番号(会社)</label>
    {{ form.postal_code }}
    {{ form.postal_code.errors }}
  </div>


  <div class="form-group">
    <label class="control-label" for="id_address">住所</label>
      {{ form.address }}
      {{ form.address.errors }}
      <p class="help-block">{{ form.address.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_phone_number">電話番号</label>
      {{ form.phone_number }}
      {{ form.phone_number.errors }}
      <p class="help-block">{{ form.phone_number.help_text }}</p>
  </div>

  <input type="hidden" name="user" value="{{ user.id }}">

  <div class="form-group">
    <div>
        <input type="submit" class="btn btn-primary" value="登録">
    </div>
  </div>

</form>
    {% endif %}
{% endblock content %}

templates/regist.html
{% extends "base.html" %}
{% block content %}
 
<form class="my-form" action="{% url 'registration:regist_save' %}" method="POST">
{% csrf_token %}
<div>
    <H2>■ ユーザー登録 ■</H2>
</div>
  <div class="form-group">
    <label for="id_username">ユーザーネーム</label>
    {{ form.username }}
    {{ form.username.errors }}
    <p class="help-block">{{ form.username.help_text }}</p>
  </div>

  <div class="form-group">
    <label for="id_email">Eメールアドレス</label>
    {{ form.email }}
    {{ form.email.errors }}
    <p class="help-block">{{ form.email.help_text }}</p>
  </div>
 
  <div class="form-group">
    <label class="control-label" for="id_password1">パスワード</label>
    {{ form.password1 }}
    {{ form.password1.errors }}
  </div>
 
  <div class="form-group">
    <label class="control-label" for="id_password2">パスワード（確認）</label>
      {{ form.password2 }}
      {{ form.password2.errors }}
      <p class="help-block">{{ form.password2.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_last_name">姓</label>
      {{ form.last_name }}
      {{ form.last_name.errors }}
      <p class="help-block">{{ form.last_name.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_first_name">名</label>
      {{ form.first_name }}
      {{ form.first_name.errors }}
      <p class="help-block">{{ form.first_name.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_ruby_last_name">ふりがな(姓)</label>
      {{ form.ruby_last_name }}
      {{ form.ruby_last_name.errors }}
      <p class="help-block">{{ form.ruby_last_name.help_text }}</p>
  </div>

  <div class="form-group">
    <label class="control-label" for="id_ruby_first_name">ふりがな(名)</label>
      {{ form.ruby_first_name }}
      {{ form.ruby_first_name.errors }}
      <p class="help-block">{{ form.ruby_first_name.help_text }}</p>
  </div>

  <div class="form-group">
    <div>
        <input type="submit" class="btn btn-primary" value="登録">
    </div>
  </div>

</form>
{% endblock content %}

templates/role.html
{% extends "base.html" %}
{% block content %}
<form class="my-form">
<div>
    <H2>■ Aqshアプリへの登録ありがとうございます ■</H2>
</div>
    <hr>

    <div>
        <a class="btn btn-primary" href="{% url 'registration:jobseeker' %}">仕事のオファーを受けたい方</a><br>
    </div>
    <br>
    <div>
        <a class="btn btn-primary" href="{% url 'registration:recruiter' %}">仕事をオファーしたい方</a><br>
    </div>
</form>
{% endblock content %}